{{- if eq .Values.authProvider "authelia" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "homeserver.authelia.names.namespace" . }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia
  namespace: {{ include "homeserver.common.names.namespace" $ }}
spec:
  repo: https://charts.authelia.com
  chart: authelia
  version: 0.10.46
  targetNamespace: {{ include "homeserver.authelia.names.namespace" . }}
  createNamespace: false
  set:
    # Set correct permissions for the pods
    # pod.securityContext.fsGroup: {{ .Values.host.gid }}
    # pod.securityContext.runAsUser: {{ .Values.host.uid }}
    # pod.securityContext.runAsGroup: {{ .Values.host.gid }}
    # Set correct permissions for PostgreSQL pods
    postgresql.volumePermissions.enabled: "true"
    postgresql.primary.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.primary.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.primary.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.readReplicas.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.readReplicas.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.readReplicas.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.backup.cronjob.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.timezone: {{ .Values.host.tz | quote }}
    # Set correct permissions for Redis pods
    redis.master.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    redis.master.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    redis.master.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    redis.replica.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    redis.replica.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    redis.replica.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
  valuesContent: |
{{- include "homeserver.common.tplvalues.render" (dict "value" (omit .Values.authelia "namespace") "context" .) | nindent 4 }}
{{- end }}
