{{- $jellyfinServices := list }}
{{- if kindIs "slice" .Values.services.jellyfin }}
  {{- $jellyfinServices = .Values.services.jellyfin }}
{{- else }}
  {{- $jellyfinServices = list .Values.services.jellyfin }}
{{- end }}
{{- range $service := $jellyfinServices }}
{{- if $service.enabled }}
{{- $kind := "app" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeserver.common.names.name" ( dict "service" $service ) | quote }}
  namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "service" $service "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
  selector: {{- include "homeserver.common.labels.matchLabels" ( dict "service" $service "context" $ ) | nindent 4 }}
{{- end }}
{{- end }}
