apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: helm-hook-install-clusterissuer-network-policy
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: helm-hook-install-clusterissuer
  policyTypes:
    - Egress
  egress:
    # -----------
    # IN CLUSTER
    # -----------

    # Allow communication with the Kubernetes API server
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 6443
