apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-hook-clusterissuer
  namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homeserver-helm-hook-clusterissuer
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homeserver-helm-hook-clusterissuer
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: helm-hook-clusterissuer
    namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
roleRef:
  kind: ClusterRole
  name: homeserver-helm-hook-clusterissuer
  apiGroup: rbac.authorization.k8s.io
