{{- if .Values.exposed }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "homeserver.common.names.name" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "homeserver.app.labels.standard" $ | nindent 4 }}
spec:
  parentRefs:
    - name: gateway
      namespace: {{ .Release.Namespace }}
      sectionName: https
  hostnames:
    {{- range .Values.hosts }}
    - {{ . }}.{{ $.Values.ingress.domain }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "homeserver.common.names.name" $ }}
          port: {{ (index .Values.ports 0).port | default (index .Values.ports 0).containerPort }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: security-chain
{{- end }}
