apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # see available values at https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    globalArguments:
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    logs:
      general:
        level: "INFO"
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        forwardedHeaders:
          insecure: false
          trustedIPs: {{- (index .Values "x-traefik").forwardedHeaders.trustedIPs | toYaml | nindent 12 }}
    providers:
      ## We need the CRD provider for Traefik's CRD resources, such as Middleware, TLS Options, etc.
      ## https://doc.traefik.io/traefik/providers/kubernetes-crd/#list-of-resources
      ##
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: false
      # Enable the Gateway API provider
      kubernetesGateway:
        enabled: true
    gateway:
      # Disable the default Gateway, we'll create our own
      enabled: false
    # Deploy the GatewayClass CRD
    gatewayClass:
      enabled: true
