apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # see available values at https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    globalArguments:
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    logs:
      general:
        level: "INFO"
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        forwardedHeaders:
          insecure: false
          # see Cloudflare's IPs at https://www.cloudflare.com/ips/
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
            - 10.0.0.0/8
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
      # Enable the Gateway API provider
      kubernetesGateway:
        enabled: true
    gateway:
      # Disable the default Gateway, we'll create our own
      enabled: false
      # Allow the Gateway to expose HTTPRoute from all namespaces
      namespacePolicy: All
    # Deploy the GatewayClass CRD
    gatewayClass:
      enabled: true
