apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: ingress
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
    {{- include "homeserver.cert-manager.ingress.annotations" . | nindent 4 }}
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s@kubernetescrd" (include "homeserver.common.names.namespace" .) "security-chain" | quote }}
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ .Values.tls.tlsSecretName }}
      hosts:
        - "{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
        - "*.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
  rules:
    {{- range $service := .Values.services }}
    {{- if and $service.enabled $service.exposed }}
    {{- if not $service.ingress }}
    {{- printf "Service %s is exposed but has no ingress paths" $service.name | fail }}
    {{- end }}
    {{- range $host := $service.ingress }}
    - host: {{ printf "%s.%s" $host $.Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeserver.common.names.name" (dict "service" $service "kind" "app") | quote }}
                port:
                  number: {{ required (printf "HTTP port is missing for service '%s'" $service.name) $service.ports.http }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.rootService }}
    {{- range $_, $service := .Values.services }}
    {{- if and (and $service.enabled $service.exposed) (eq $service.name $.Values.ingress.rootService) }}
    - host: {{ $.Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homeserver.common.names.name" ( dict "service" $service "kind" "app" ) | quote }}
                port:
                  number: {{ required (printf "HTTP port is missing for service '%s'" $service.name) $service.ports.http }}
    {{- end }}
    {{- end }}
    {{- end }}
