apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
spec:
  headers:
    # this Strict-Transport-Security (STS) config is valid for submission to the HSTS preload list
    # submit at https://hstspreload.org
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      X-XSS-Protection: "1; mode=block"
      Cross-Origin-Resource-Policy: "cross-origin"
      Cross-Origin-Opener-Policy: "same-origin"
      Cross-Origin-Embedder-Policy: "unsafe-none"
      Referrer-Policy: "strict-origin-when-cross-origin"
    contentSecurityPolicy: >-
      default-src 'self' data: blob: https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https:;
      style-src 'self' 'unsafe-inline' data: https:;
      img-src 'self' data: blob: http: https:;
      font-src 'self' data: https:;
      frame-ancestors 'self' https://{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }} https://*.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }};
      form-action 'self' https:;
      base-uri 'self';
      connect-src 'self' data: blob: ws: wss: https:;
      media-src 'self' data: blob: http: https:;
      worker-src 'self' data: blob:;
      frame-src 'self' data: blob: https:;
      object-src 'none';
    permissionsPolicy: >-
      accelerometer=(),
      ambient-light-sensor=(),
      battery=(),
      cross-origin-isolated=(),
      display-capture=(),
      document-domain=(),
      encrypted-media=(),
      execution-while-not-rendered=(),
      execution-while-out-of-viewport=(),
      gyroscope=(),
      keyboard-map=(),
      magnetometer=(),
      midi=(),
      navigation-override=(),
      payment=(),
      publickey-credentials-get=(),
      screen-wake-lock=(),
      sync-xhr=(),
      usb=(),
      web-share=(),
      xr-spatial-tracking=(),
      interest-cohort=()
