apiVersion: v2
name: homeserver-app
description: Generic application chart for homeserver services
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../charts/library"
