{{- if eq .Values.authProvider "authentik" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "homeserver.authentik.names.namespace" . }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: {{ include "homeserver.common.names.namespace" $ }}
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  version: 2025.8.4
  targetNamespace: {{ include "homeserver.authentik.names.namespace" . }}
  createNamespace: false
  set:
    # Authentik is already exposed via Gateway API in this Chart
    server.ingress.enabled: "false"
    # Set correct permissions for the pods
    postgresql.volumePermissions.enabled: "true"
    postgresql.primary.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.primary.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.primary.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.readReplicas.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.readReplicas.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.readReplicas.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.podSecurityContext.fsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.containerSecurityContext.runAsUser: {{ .Values.host.uid }}
    postgresql.backup.cronjob.containerSecurityContext.runAsGroup: {{ .Values.host.gid }}
    postgresql.backup.cronjob.timezone: {{ .Values.host.tz | quote }}
  valuesContent: |
{{- include "homeserver.common.tplvalues.render" (dict "value" (omit .Values.authentik "namespace") "context" .) | nindent 4 }}
{{- end }}
