apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authentik
  namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: forwardauth-authentik
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
spec:
  forwardAuth:
    address: {{ printf "http://ak-outpost-authentik-embedded-outpost.%s.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik" (include "homeserver.authentik.names.namespace" .) | quote }}
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-entitlements
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - X-authentik-meta-jwks
      - X-authentik-meta-outpost
      - X-authentik-meta-provider
      - X-authentik-meta-app
      - X-authentik-meta-version
