---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: homeserver-reference-grant
  namespace: {{ include "homeserver.authentik.names.namespace" . | quote }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  to:
    - group: ""
      kind: Service
      name: authentik-server
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-route
  namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: authentik-route
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "context" $ ) | nindent 4 }}
spec:
  parentRefs:
    - name: gateway
      sectionName: https
      namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
  hostnames:
    - {{ printf "authentik.%s" $.Values.ingress.domain | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: authentik-server
          port: 80
          kind: Service
          namespace: {{ include "homeserver.authentik.names.namespace" . | quote }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: security-chain-no-auth
