apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-egress-policy
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # -------------
    # IN NAMESPACE
    # -------------

    # Allow internal namespace communication
    - to:
        - podSelector: {}

    # -----------
    # IN CLUSTER
    # -----------

    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

    # Allow communication with the Authentik server
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "homeserver.authentik.names.namespace" . | quote }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: authentik

    # --------------------
    # OUTSIDE THE CLUSTER
    # --------------------

    # Allow all outgoing connections
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
