apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-ingress-policy
  namespace: {{ include "homeserver.common.names.namespace" $ | quote }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow internal namespace communication
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "homeserver.common.names.namespace" . | quote }}
    # Allow traffic from the Traefik ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
