{{- if .Values.services.homepage.enabled }}
{{- $service := .Values.services.homepage  }}
{{- $kind := "app" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups: # see https://github.com/gethomepage/homepage/pull/2003
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
    namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}
