name: Run Renovate

on:
  schedule:
    # Renovate runs hourly, every hour on the minute 0.
    # Adjust this cron schedule as needed for your desired frequency.
    # For example, '0 0 * * *' would run once a day at midnight UTC.
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      # Required for cloning the repository
      contents: write
      # Required for creating and updating pull requests
      pull-requests: write
      # Required for writing commit statuses (optional, but good for CI checks)
      statuses: write
      # Required for reading packages (especially from GHCR)
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # 'audit' for logging all attempts, 'restrict' for strict control

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.2 # Official Renovate action
        with:
          configurationFile: .github/renovate.json # Path to your Renovate config
          # Command-line arguments for Renovate (optional, but useful for debugging)
          # command: "renovate --verbose"
        env:
          # This GITHUB_TOKEN is provided by GitHub Actions and has the permissions
          # defined in the 'permissions' block above. It's used by Renovate
          # to clone the repo, create PRs, etc.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
