name: Run Renovate

on:
  schedule:
    # Renovate runs hourly, every hour on the minute 0.
    # Adjust this cron schedule as needed for your desired frequency.
    # For example, '0 0 * * *' would run once a day at midnight UTC.
    #
    # run “At 00:00 everyday”
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab
    inputs:
      dryRun:
        description: Dry Run
        default: false
        required: false
        type: boolean
      logLevel:
        description: Log Level
        type: choice
        default: info
        options:
          - debug
          - info

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      # Required for cloning the repository
      contents: write
      # Required for creating and updating pull requests
      pull-requests: write
      # Required for writing commit statuses (optional, but good for CI checks)
      statuses: write
      # Required for reading packages (especially from GHCR)
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # 'audit' for logging all attempts, 'restrict' for strict control

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.2 # Official Renovate action
        with:
          configurationFile: .github/renovate.json5 # Path to your Renovate config
          # Command-line arguments for Renovate (optional, but useful for debugging)
          # command: "renovate --verbose"
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun == true }}
          RENOVATE_AUTODISCOVER: false
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
